### ISSUE TITLE
Version Error When Running Docker Image

### ISSUE THREAD

**Issue by lassestahnke** [nipreps/fmriprep-rodents#41]
Hi, 
I'd like to use FMRIPrep-Rodent, but encountered a 'Version Error' when trying to run the docker image. 

I built the docker images with the following command:
 `docker build github.com/poldracklab/fmriprep-rodents`
So I am using the newest version of the repository (Nov 10, 2021).

After tagging my image as 'fmri_prep_rodent", I ran the following command to run the image in a container:
`docker run fmri_prep_rodent`

Which results in the following Error Message:
`Traceback (most recent call last):
File "/usr/local/miniconda/bin/fprodents", line 8, in <module>
sys.exit(main())
File "/usr/local/miniconda/lib/python3.7/site-packages/fprodents/cli/run.py", line 17, in main
parse_args()
File "/usr/local/miniconda/lib/python3.7/site-packages/fprodents/cli/parser.py", line 540, in parse_args
parser = _build_parser()
File "/usr/local/miniconda/lib/python3.7/site-packages/fprodents/cli/parser.py", line 68, in _build_parser
currentv = Version(config.environment.version)
File "/usr/local/miniconda/lib/python3.7/site-packages/packaging/version.py", line 266, in __init__
raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''`

I'd appreciate any help on resolving this issue.

**Comment by eilidhmacnicol** [comment]
Hi @lassestahnke - thank you for posting your issue!

I think this is probably stems from a lack of documentation, so thanks for your patience. Could you try building the docker file with the makefile in the repo? i.e.: 
1. clone the repo locally
2. navigate to the local directory
3. run `make docker-build tag=fmri_prep_rodent`

Let me know how that goes.

**Comment by lassestahnke** [comment]
Hi @eilidhmacnicol thank you for your response!

Unfortunately, building the docker image with the make file hasn't resolved my issue. The same error message appears. Do you have any other ideas on how to solve it?
