### ISSUE TITLE
Singularity: No space left on device

### ISSUE THREAD

**Issue by Hierakonpolis** [nipreps/fmriprep-rodents#46]
The processing pipeline fails because of errors such as:
`OSError: [Errno 28] No space left on device: '/opt/conda/lib/python3.8/site-packages/skimage/data/../data/brick.png' -> '/home/fmriprep/.cache/scikit-image/0.18.3/data/../data/brick.png'`
I tried setting the workdir explicitly following https://github.com/nipreps/fmriprep/issues/2120 and https://github.com/nipreps/fmriprep/issues/1291 and the issue remains.

### What version of fMRIPrep are you using?
Latest fmriprep-rodents from docker as of April 19th
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity
### What is the exact command-line you used?
```
singularity run --cleanenv ~/singularity_images/fmriprep-rodents19042022.simg /home/mri/dataset /home/mri/test_fmriprep participant --fs-license-file licensefile -w ~/scratchdir
```

### Have you checked that your inputs are BIDS valid?
The validator checks out
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
No

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/nibabel.py", line 396, in _run_interface
    self._results["out_file"] = _advanced_clip(
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/nibabel.py", line 517, in _advanced_clip
    from skimage.morphology import ball
  File "/opt/conda/lib/python3.8/site-packages/skimage/__init__.py", line 135, in <module>
    from .data import data_dir
  File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 270, in <module>
    _init_pooch()
  File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 262, in _init_pooch
    _fetch(filename)
  File "/opt/conda/lib/python3.8/site-packages/skimage/data/__init__.py", line 222, in _fetch
    shutil.copy2(gh_repository_path, resolved_path)
  File "/opt/conda/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.8/shutil.py", line 272, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/opt/conda/lib/python3.8/shutil.py", line 163, in _fastcopy_sendfile
    raise err from None
  File "/opt/conda/lib/python3.8/shutil.py", line 149, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 28] No space left on device: '/opt/conda/lib/python3.8/site-packages/skimage/data/../data/brick.png' -> '/home/fmriprep/.cache/scikit-image/0.18.3/data/../data/brick.png'
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

**Comment by eilidhmacnicol** [comment]
This looks like an issue with the mounted volumes for singularity rather than a problem with fmriprep-rodents, since similar issues were found in other NiPreps tools (see https://github.com/nipreps/mriqc/issues/850#issuecomment-894769976 and https://sylabs.io/guides/2.5/user-guide/troubleshooting.html)

**Comment by effigies** [comment]
This looks like an issue with scikit-learn downloading files we're not requesting. Are we pinning a specific version? I remember them fixing something like this a while back.

**Comment by eilidhmacnicol** [comment]
> Are we pinning a specific version

No - in fact I don't think it's listed as a dependency anywhere (outside of the GitHub action: https://github.com/nipreps/fmriprep-rodents/blob/edfe415aa2fc7c2988b5cf7e3d6824269f260ad0/.github/workflows/pythonpackage.yml#L70). Does that ring any bells? 

Otherwise, it might be a problem with one of the dependencies. I'll try to recreate with the latest singularity image.

**Comment by Hierakonpolis** [comment]
As far as you know, would it be at all possible to find a workaround to this issue in the meantime, for example to let singularity provide some extra space for the image?

**Comment by effigies** [comment]
This is the relevant issue: https://github.com/scikit-image/scikit-image/issues/6069

We need to pin scikit-image >= 0.19 in the docker container.

**Comment by Hierakonpolis** [comment]
Is there any workaround I could use in the meantime, for example to allow for some writable space that would prevent this error from happening?

**Comment by eilidhmacnicol** [comment]
Okay, so I have been trying to work out how to change `.circleci/config.yml` for a good chunk of the afternoon, so that tags actually push to dockerhub. @oesteban @effigies - do either of you have the bandwidth to help with this change?

**Comment by effigies** [comment]
> Is there any workaround I could use in the meantime, for example to allow for some writable space that would prevent this error from happening?

Bind a writeable directory into the data directory that failed to be written to.
